# Generated by Django 4.2 on 2025-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_renthousemodel_sellhousemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellhousemodel',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='sellhousemodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sellhousemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='sellhousemodel',
            name='address',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='sellhousemodel',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
