# Generated by Django 4.2 on 2025-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_sellhousemodel_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellhouse',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='sellhouse',
            name='housename',
        ),
        migrations.AddField(
            model_name='sellhouse',
            name='address',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='sellhouse',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='sellhouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AlterField(
            model_name='sellhouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
