# Generated by Django 4.2 on 2025-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_sellhouse_adress_remove_sellhouse_housename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_sellhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('address', models.CharField(default='Not provided', max_length=255)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='houses/')),
            ],
        ),
        migrations.DeleteModel(
            name='renthousemodel',
        ),
        migrations.DeleteModel(
            name='sellhouse',
        ),
        migrations.DeleteModel(
            name='sellhousemodel',
        ),
    ]
