# Generated by Django 4.2 on 2025-05-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_sellhouse_delete_renthousemodel_delete_sellhouse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='renthouse',
            new_name='add_renthouse',
        ),
    ]
