# Generated by Django 4.2 on 2025-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_renthouse_add_renthouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_renthouse',
            name='image',
            field=models.ImageField(upload_to='rent_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='House_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
